python roll_with_const.py --roll_indx 0
python roll_with_const.py --roll_indx 1
python roll_with_const.py --roll_indx 2
python roll_with_const.py --roll_indx 3
python roll_with_const.py --roll_indx 4
python roll_with_const.py --roll_indx 5
python roll_with_const.py --roll_indx 6
python roll_with_const.py --roll_indx 7
python roll_with_const.py --roll_indx 8
