python u_coverage.py --template_weight 0
python u_coverage.py --template_weight 3
python u_coverage.py --template_weight 6
python u_coverage.py --template_weight 12
python u_coverage.py --template_weight 24
python u_coverage.py --template_weight 50
python u_coverage.py --template_weight 100
python u_coverage.py --template_weight 200
python u_coverage.py --template_weight 500
