python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 0 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 1 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 2 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 3 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 4 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 5 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 6 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 7 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 8 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 9
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 0 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 1 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 2 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 3 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 4 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 5 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 6 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 7 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 8 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 9
