python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 0 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 10 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 20 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 30 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 1 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 11 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 21 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 31 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 35 
python clouds_baseline.py --rolling_nslice 2 --cloud_offset_year 36
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 0 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 10 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 20 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 30 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 1 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 11 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 21 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 31 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 35 
python clouds_baseline.py --rolling_nslice 3 --cloud_offset_year 36
