python ddf_sl.py --ddf_season_frac 0
python ddf_sl.py --ddf_season_frac 0.05
python ddf_sl.py --ddf_season_frac 0.1
python ddf_sl.py --ddf_season_frac 0.15
python ddf_sl.py --ddf_season_frac 0.2
python ddf_sl.py --ddf_season_frac 0.25
python ddf_sl.py --ddf_season_frac 0.3
python ddf_sl.py --ddf_season_frac 0.35
python ddf_sl.py --ddf_season_frac 0.4
